// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "skyiptime4179"
#define SECRET_PASS "skylife179"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a1wxq764mrcpq3-ats.iot.ap-northeast-2.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICiTCCAXGgAwIBAgIVAPUKuspeAtfZQ96k57Jxrx70GyYOMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMTEwMTkxMDQw
MTlaFw00OTEyMzEyMzU5NTlaMBgxFjAUBgNVBAMTDU15TUtSV2lGaTEwMTAwWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAATPkOc2YSC/O1+SKGJpkmkIs9pHxsNTHIAO
0vmeT44+X1BucCdS7oR7k1NdFuHB0tdrca4CQPGPVx7G/d+ly3p1o2AwXjAfBgNV
HSMEGDAWgBTBVy2bV+JheFGT4Fvd8b3MNfsnejAdBgNVHQ4EFgQUDWAmrxOYvVpi
UApNZvEjx4i2Qn8wDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZI
hvcNAQELBQADggEBAIPsgEF9eCyB0/uROeg+jBbIuCtpyI8xcHkBXV24dyiWLV2/
107wUezS6QERNKL2Mk/U5sodq66FWjmJWiIJT/gfk0J/hsIMcgOyEUEDGNg4EQjM
HSSGFeUT+neLCqwCm9H5U4pLPzs0qvQJapmA9ImbCmKaeEYqN1/iGpGu258SSqRR
nJy8TfoofC3qvgUgW/FYcmTjH1NwC25QECEQGVDKc1c6I0yMeaV7LwN0xenqcq4g
MLKLtHLardsjyH325saeNrIFNuSdkcU1M/ET5o0Ve9V/mUgFXcxgYwkyRkCPyl9w
Or3njwPHxAIuBvZ+eun+M7aU4lQVePFT0hThO9M=
-----END CERTIFICATE-----
)";
